export const todosActions = {
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
    REQUEST_TODOS: 'REQUEST_TODOS',
    RECEIVE_TODOS: 'RECEIVE_TODOS',
    SET_FILTER: 'SET_FILTER',
    FETCH_TODOS: 'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
};
